name: Markdown CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'  
      - run: npm install alex
      
      - name: Alex.js 
        run: npm run test-alex

      - name: Markdown lint
        if: success() || failure()
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          ignore_files: node_modules
          config_file: "mdlint.json"

      - name: Check for 404 links      
        if: success() || failure() 
        uses: restqa/404-links@1.0.1
        with:
          path: .
          ignore: 'https://cucumber.io,https://docs.data.ukho.gov.uk,https://github.com,https://en.wikipedia.org,https://www.nationalarchives.gov.uk'
